language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.5.2

install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install

script:
  - django-admin.py test --settings=nested_formset.test_settings nested_formset
