language: python
python:
  - "2.7"

env:
  - DJANGO_SPEC=Django==1.5.2
  - DJANGO_SPEC=https://www.djangoproject.com/download/1.6b2/tarball/\#egg\=Django

install:
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - django-admin.py test --settings=nested_formset.test_settings nested_formset
