language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_SPEC=Django==1.5.8
  - DJANGO_SPEC=Django==1.6.5
  - DJANGO_SPEC=https://github.com/django/django/zipball/master\#egg\Django

install:
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - django-admin.py test --settings=nested_formset.test_settings nested_formset
